name: Build Unsigned Debug APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        # https://github.com/marketplace/actions/setup-android-sdk-tools

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Step 1: Build the unsigned debug APK
      - name: Build Unsigned Debug APK
        # run: ./gradlew assembleRelease
        run: ./gradlew assembleDebug

      # Step 2: Upload the unsigned APK as a workflow artifact
      - name: Upload Unsigned Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-v${{ env.VERSION_NAME }}
          path: app/build/outputs/apk/debug/app-debug.apk
